eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: students
            uri: http://localhost:8090
            predicates:
              - Path=/students/**
          - id: schools
            uri: http://localhost:8070
            predicates:
              - Path=/schools/**

management:
  tracing:
    sampling:
      probability: 1.0
