eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8070
spring:
  application:
    name: school
  datasource:
    url: jdbc:mysql://localhost:3306/school
    username: mehdi

application:
  config:
    students-url: http://localhost:8090/students

management:
  tracing:
    sampling:
      probability: 1.0
